### ISSUE TITLE
Set wait time to take the snapshot

### ISSUE THREAD

**Issue by sergiogragera** [vladocar/screenshoteer#1]
Add the possibility to indicate a parameter to wait to take the screenshot, or even be able to indicate which element of the DOM has to be visible.

If you load the url https://es.hboespana.com/movies/overview/3b1f95c-00fe50831f9, screenshot is HBO icon because the page is loading.

**Comment by vladocar** [comment]
That is great suggestion! I'm working on it :)

**Comment by vladocar** [comment]
I just added the new --waitfor parameter, time in milliseconds.  You need to do the update: npm i -g screenshoteer

And do this:
screenshoteer --url https://es.hboespana.com/movies/overview/3b1f95c-00fe50831f9 --waitfor 4000
