### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by DanielRuf** [vladocar/screenshoteer#11]
I see that https://github.com/vladocar/screenshoteer/issues/4 was closed.

But we should write some small tests to test on Travis CI an so on and catch regressions / bugs.

**Comment by vladocar** [comment]
After finding various bugs in the project .. I can say unit test does matter.

**Comment by vladocar** [comment]
@DanielRuf If you can write some tests for Travis CI it would be great :) Thanks!

**Comment by DanielRuf** [comment]
Is this resolved? Otherwise I'll recommend a testing framework and prepare the CI script.

**Comment by vladocar** [comment]
I thought you lost interest..

If you can recommend a testing framework and prepare the CI script, it would be super helpful :)

Thanks!

**Comment by DanielRuf** [comment]
> I thought you lost interest..

I just had not much time in my holiday (2 weeks).

**Comment by DanielRuf** [comment]
Jest is often used. I'll check if this would be perfect here.

**Comment by vladocar** [comment]
> I  just had not much time in my holiday (2 weeks).

 My recommendation don't think about work when you are on holiday :) Just press the "pause" button for two weeks. You can always contribute after your holiday :)
