### ISSUE TITLE
Allow local paths

### ISSUE THREAD

**Issue by ISNIT0** [vladocar/screenshoteer#20]
Would love to be able to do:
```bash
screenshoteer --url=./test-output.html
```

**Comment by vladocar** [comment]
You can, just: 
screenshoteer --url file:///Users/../index.html

First open the html file in the browser then copy paste the url path from the browser.

**Comment by ISNIT0** [comment]
Ahh, so it needs to be an absolute path then?

**Comment by vladocar** [comment]
Yes, file:/// plus absolute path.
