### ISSUE TITLE
Password-protected pages

### ISSUE THREAD

**Issue by gilgongo** [vladocar/screenshoteer#23]
Great, great work on screenshoteer! I've been looking for a good scriptable solution to screen shots for a long time. 

One question: what, if any, strategies might there be to get screenshoteer to work with URLs that require authentication beyond basic http auth?

**Comment by vladocar** [comment]
Thanks!

> One question: what, if any, strategies might there be to get screenshoteer to work with URLs that require authentication beyond basic http auth?

I'm open to suggestions .. and new ideas.

**Comment by gilgongo** [comment]
I wondered, for example whether screenshoteer could be configured to look for a username/password field on the page and, if found, supply credentials. Perhaps a config file containing:

```
User_field: [nameofinputfield]
Passwd_field: [nameofinputfield]

Username: johndoe@domain.com
Password: password
```

**Comment by vladocar** [comment]
For this kind of scenario I think is the best to make custom scripts for the targeted site.

Here are some examples: https://github.com/checkly/puppeteer-examples/tree/master/3.%20login

**Comment by gilgongo** [comment]
Ah OK - will have a look. Thanks!
