### ISSUE TITLE
Add tests and setup CI/CD

### ISSUE THREAD

**Issue by anishkny** [vladocar/screenshoteer#4]
Can send out a PR let me know. Azure Pipelines offers free CI/CD on all three platforms.

**Comment by vladocar** [comment]
I'm not sure what you mean?

**Comment by anishkny** [comment]
It is considered a best practice to have unit tests for a code repository. I am proposing adding unit tests to this repo to ensure that bugs are caught early in the process. CI/CD is a process that ensures code is checked into the main repo and tested often. You can use [Azure Pipelines](https://azure.microsoft.com/en-us/services/devops/pipelines/) - a hosted CI/CD provider which offers free test pipelines for Windows/Mac/Linux for open source projects.

**Comment by vladocar** [comment]
I would normally agree with you about the unit test. But this project is for now 50 lines of code. You will spend more time making the unit tests than making entire project from scratch. I think in this small project unit tests are not necessary.

Thank for your suggestion.
