### ISSUE TITLE
waitUntil parameter

### ISSUE THREAD

**Issue by parweb** [vladocar/screenshoteer#5]
maybe add --waitUntil="networkidle2" parameter

`await page.goto('https://news.ycombinator.com', {waitUntil: 'networkidle2'});`

waitUntil can be either:
load - consider navigation to be finished when the load event is fired.
domcontentloaded - consider navigation to be finished when the DOMContentLoaded event is fired.
networkidle0 - consider navigation to be finished when there are no more than 0 network connections for at least 500 ms.
networkidle2 - consider navigation to be finished when there are no more than 2 network connections for at least 500 ms.

**Comment by vladocar** [comment]
Im not sure why you need "networkidle2" parameter?
