### ISSUE TITLE
.DS_Store

### ISSUE THREAD

**Issue by isaacanthony** [vladocar/screenshoteer#7]
You accidentally committed your .DS_Store. It's in the .gitignore but you must have committed it prior to adding it there. Depending on deployment process, this could be a security issue. https://www.intego.com/mac-security-blog/possible-security-issue-involving-ds_store-files-on-web-servers/

**Comment by vladocar** [comment]
Thanks!
Yes, I forgot to put .gitignore first time. I deleted the .DS_Store from github.
